<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Acceso extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Acceso_model');
    } 

  
    function index()
    {
      $tit['errorlogin'] = "";
      $this->load->view('acceso/login',$tit);
     
    }

    function autenticar()
    {   
 
      $theemail     = $this->input->post('Email');
      $thepassword  = $this->input->post('Password');
      $loginvalid   = "";

      $approve = $this->Acceso_model->get_acceso_adminc($theemail);
      if($approve) {
        if(password_verify($thepassword, $approve['Password'])) 
        {
          $this->session->set_userdata('iduser',$approve['id_User']);
          $this->session->set_userdata('nameu',$approve['Name']);
          $this->session->set_userdata('email',$approve['Email']);
          $this->session->set_userdata('active',$approve['Active']);
            
          if($approve['Type_User']=="D") {

            $this->load->model('Doctor_model');
            $this->load->model('Document_model');
            $this->load->model('Credentials_model');

            $user_ide = $approve['id_User'];
            $doctor = $this->Doctor_model->get_doctor_byuser($user_ide);
            $theiddoctor = $doctor;
            $data['doctor'] = $this->Doctor_model->get_user_doctor($user_ide);
            $data['documents'] = $this->Document_model->get_all_document2();
            $data['credentials'] = $this->Credentials_model->get_all_credentials_doctor($theiddoctor);
            $data['mymessage'] = null;

            if($approve['Active']==0) { // DR register but not approve 
              $this->load->view('head');
              $this->load->view('doctor/content_credentials_dr',$data);
              $this->load->view('footer');
            }
            if($approve['Active']==1)  // Dr Aprrove
            {
              $this->load->view('head');
              $this->load->view('doctor/home');
              $this->load->view('footer');
            }
          }
          else
          {
            // Enter Patient 
            $this->load->model('Patient_model');
            $this->load->model('Doctor_model');
            $this->load->model('Specialist_model');
            $this->load->model('Language_model');
            $user_ide = $approve['id_User'];
            $patient = $this->Patient_model->get_patient_byuser($user_ide);
            $theidpatient = $patient;
            $data['patient']        = $this->Patient_model->get_user_patient($user_ide);
            $data['doctor']         = $this->Doctor_model->get_all_doctor_name();
            $data['specialities']   = $this->Specialist_model->get_all_specialist();
            $data['languages']      = $this->Language_model->get_all_language();
            $data['mymessage']      = null;

            $this->load->view('head_patient');
            $this->load->view('patient/home',$data);
            $this->load->view('footer');

          }
        }
        else
        {
          $tit['errorlogin'] = "Password Invalid - Try again -";
          $this->load->view('acceso/login',$tit);
        }
      }
      else
      {
          $tit['errorlogin'] = "Email Invalid - Try again -";
          $this->load->view('acceso/login',$tit);
      }
    } 

   
    function close()
    {
      $this->session->unset_userdata('iduser');
      $this->session->unset_userdata('nameu');
      $this->session->unset_userdata('email');
      $this->session->unset_userdata('active');
      $this->session->sess_destroy();
      $tit['errorlogin'] = "";
      $this->load->view('acceso/login',$tit);
    }

    function restore()
    { 
      $tit['titulo1'] = "";
      $tit['titulo2'] = "";
      $tit['ind'] = "no";
      $this->load->view('acceso/restore');
    }

    function genpass()
    {
      $this->load->model('User_model');
      $correodestino = $this->input->post('Email');
      //RUTINA PARA GENERAR CLAVE ALEATORIA
      $cadena = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
      $longitudCadena=strlen($cadena);    
      $pass = "";
      $longitudPass=6;    
      for($i=1 ; $i<=$longitudPass ; $i++){
        $pos=rand(0,$longitudCadena-1);     
        $pass .= substr($cadena,$pos,1);
      }
      $nuevaClave = $pass;
      // FIN DE LA RUTINA
      //$grabarClave = hash($nuevaClave);
      $hash = password_hash($nuevaClave, PASSWORD_DEFAULT, array("cost" => 9));
      // Grabar la clave ENCRIPTADA 
      $to = $correodestino;
      $subject = "Now you have a new password";
      $txt = "Your new password is ".$nuevaClave;
      $headers = "MIME-Version: 1.0" . "\r\n";
      $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
      // More headers
      $headers .= 'From: <admin@medical.com>' . "\r\n";
      $enviado = mail($to,$subject,$txt,$headers);

      $mensaje = "";
      if($enviado) {
        $params = array('Password' => $hash,);
        $this->User_model->update_password($correodestino,$params);
        $mensaje = "New Password send succesfully ";
      }
      else
      {
        $mensaje = "'Can´t send email' or 'No count with this email -try again'";
      }

      $tit['errorlogin'] = $mensaje;
      $this->load->view('acceso/login',$tit);
    }
    
}
