<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Booking extends CI_Controller
{
  function __construct()
  {
      parent::__construct();
      $this->load->model('Booking_model');
  } 

  function add()
  {
    
    if(isset($_POST) && count($_POST) > 0)     
    {

      $iddoctor         = $this->input->post('iddoctor');
      $idpatient        = $this->input->post('idpatient');
      $datebooking      = $this->input->post('dateappointment');
      $iddoctorservice  = $this->input->post('iddoctorservice');

      $databooking = array(
          'id_Doctor' => $iddoctor,
          'id_Patient' => $idpatient, 
          'id_Doctor_Service' => $iddoctorservice,
          'Date_Booking' => $datebooking);

      //$strbooking = $this->db->insert_string('booking', $databooking);
      //$insert_dr  = $this->db->query($strbooking);

      //$theiddr    = $this->db->insert_id();

      /* SEND EMAIL */
      /*
      $to = $theemail;
      $subject = "Welcome, Register Succesfully !";
        $txt = "We received your application #".$theiddr." You completed the first step. The next step is login and upload your credentials. When you completed this requirement we will review your application within 3 working days. In case of aprovement we will send you an email. Thank you.";
        $headers = "MIME-Version: 1.0" . "\r\n";
        $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
        // More headers
        $headers .= 'From: <admin@domain.com>' . "\r\n";
        $enviado = mail($to,$subject,$txt,$headers);

      */


      $this->load->model('Patient_model');
      $this->load->model('Doctor_model');
      $this->load->model('Specialist_model');
      $this->load->model('Language_model');
      $this->load->model('Nationality_model');
      $this->load->model('StreamTool_model');
      $this->load->model('Doctorservice_model');
      $this->load->model('Booking_model');
      $data['patient']        = $this->Patient_model->get_patient($idpatient);
      $data['booking']        = $this->Booking_model->get_booking($idpatient);
      $data['doctor']         = $this->Doctor_model->get_doctor($iddoctor);
      $data['specialities']   = $this->Specialist_model->get_all_specialist();
      $data['languages']      = $this->Language_model->get_all_language();
      $data['nationality']    = $this->Nationality_model->get_all_nationality2();
      $data['streamtool']     = $this->StreamTool_model->get_all_streamtool();
      $data['dateappointment'] = $datebooking;
      $data['mymessage']      = null;

      $this->load->view('head_patient');
      $this->load->view('patient/patient_reservations',$data);
      $this->load->view('footer');
        
    }
  }

  function doctors_booking()
  {
      $this->load->model('Patient_model');
      $this->load->model('Doctor_model');
      $this->load->model('Booking_model');
      $userme                 = $this->session->userdata('iduser');
      $iddr                   = $this->Doctor_model->get_doctor_byuser($userme);
      $data['doctor']         = $this->Doctor_model->get_doctor($iddr);
      $data['booking']        = $this->Booking_model->get_doctors_booking($iddr);
      $data['mymessage']      = null;

      $this->load->view('head');
      $this->load->view('booking/content_booking_dr',$data);
      $this->load->view('footer');
        
  }
  function patient_booking()
  {
      $this->load->model('Patient_model');
      $this->load->model('Doctor_model');
      $this->load->model('Booking_model');
      $userme                 = $this->session->userdata('iduser');
      $idpa                   = $this->Patient_model->get_patient_byuser($userme);
      $data['patient']        = $this->Patient_model->get_patient($idpa);
      $data['booking']        = $this->Booking_model->get_patient_booking($idpa);
      $data['mymessage']      = null;

      $this->load->view('head_patient');
      $this->load->view('booking/content_booking_pa',$data);
      $this->load->view('footer');
        
  }
  function booking_confirmation($idbooking)
  {
      $this->load->model('Patient_model');
      $this->load->model('Doctor_model');
      $this->load->model('Booking_model');
      $this->load->model('StreamTool_model');
      $userme                 = $this->session->userdata('iduser');
      $iddr                   = $this->Doctor_model->get_doctor_byuser($userme);
      $data['doctor']         = $this->Doctor_model->get_doctor($iddr);
      $data['booking']        = $this->Booking_model->get_doctors_booking($iddr);
      $data['streamtool']     = $this->StreamTool_model->get_all_streamtool();
      $data['mymessage']      = null;

      $this->load->view('head');
      $this->load->view('booking/confirmation_booking',$data);
      $this->load->view('footer');
        
  }
  function confirm($idbooking)
  {
    /*
      This Function record the Booking Confirmed (Status = 2)
      assign a link and medium of the meeting
    */
    $this->load->model('Patient_model');
    $this->load->model('Doctor_model');
    $this->load->model('Booking_model');
    $this->load->model('StreamTool_model');

    $streamtool             = $this->input->post('Stream_Tool');
    $streamlink             = $this->input->post('Stream_Link');
    $param                  = array(
      'id_Stream_Tool'      => $streamtool,
      'Link_Stream'         => $streamlink,
      'id_Status_Meeting'   => 2
    );

    
    $resultado              = $this->Booking_model->confirm_booking($idbooking,$param);
    
    $userme                 = $this->session->userdata('iduser');
    $iddr                   = $this->Doctor_model->get_doctor_byuser($userme);
    $data['doctor']         = $this->Doctor_model->get_doctor($iddr);
    $data['booking']        = $this->Booking_model->get_doctors_booking($iddr);
    $data['streamtool']     = $this->StreamTool_model->get_all_streamtool();
    $data['mymessage']      = "Confirmation a Appointment Successfully";
    $this->load->view('head');
    $this->load->view('booking/content_booking_dr',$data);
    $this->load->view('footer');
        
  }
  function booking_cancelation($idbooking)
  {
    $this->load->model('Patient_model');
    $this->load->model('Doctor_model');
    $this->load->model('Booking_model');
    $result                 = $this->Booking_model->cancel_booking($idbooking);
    $userme                 = $this->session->userdata('iduser');
    $iddr                   = $this->Doctor_model->get_doctor_byuser($userme);
    $data['doctor']         = $this->Doctor_model->get_doctor($iddr);
    $data['booking']        = $this->Booking_model->get_doctors_booking($iddr);
    $data['mymessage']      = null;

    $this->load->view('head');
    $this->load->view('booking/content_booking_dr',$data);
    $this->load->view('footer');
        
  }
}