<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com

 	 Sitio es Banco o Tiro
 */
 
class Credentials extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Credentials_model');
    } 

    /*
     * Editing a Credential
     */

    function edit($idcredentials)
    {   
      
      $this->load->model('Doctor_model');
      $this->load->model('Doctorservice_model');
      $userme = $this->session->userdata('iduser');
      $iduserdoctor = $this->session->userdata('userdoctor');
      $doctor = $this->Doctor_model->get_doctor_byuser($userme);
      $theiddoctor = $doctor;
      $data['doctor'] = $this->Doctor_model->get_user_doctor($userme);
      $data['doctorservice'] = $this->Doctorservice_model->get_doctor_service_byid($id_doctor_service);
      $data['mymessage'] = null;
      $this->load->view('head');
      $this->load->view('doctorservice/content_edit_doctor_service',$data);
      $this->load->view('footer');
    }

    function update($idcredentials)
    { 
      $params = array(
      'id_Doctor' => $this->input->post('idDoctor'),
      'Day_Week' => $this->input->post('day_week'),
      'Initial_Hour' => $this->input->post('hour'),
      'GMT' => $this->input->post('MYGMT'),
      );
      $update_schedule = $this->Doctorservice_model->update_doctor_service($id_doctor_service,$params);
      if($update_schedule) {
        $data['mymessage'] = "Record Updated Succesfully";
      }
      else {
         $data['mymessage'] = "Oops we had a problem updating record";
      }
      $this->load->model('Doctor_model');
      $this->load->model('Doctorservice_model');
      $userme = $this->session->userdata('iduser');
      $iduserdoctor = $this->session->userdata('userdoctor');
      $doctor = $this->Doctor_model->get_doctor_byuser($userme);
      $theiddoctor = $doctor;
      $data['doctor'] = $this->Doctor_model->get_user_doctor($userme);
      $data['doctorservice'] = $this->Doctorservice_model->get_doctor_service_byid($id_doctor_service);
      $this->load->view('head');
      $this->load->view('doctorservice/content_edit_doctor_service',$data);
      $this->load->view('footer');
    } 

    /*
     * Deleting Credentials
     */
    function remove($idcredentials)
    {
      $delete_credential = $this->Credentials_model->delete_credentials($idcredentials);

      if($delete_credential) {
        $data['mymessage'] = "Record Deleted Succesfully";
      }
      else {
         $data['mymessage'] = "Oops we had a problem deleting record";
      }

      $this->load->model('Document_model');
      $this->load->model('Doctor_model');
      $this->load->model('Credentials_model');
      $this->load->model('User_model');

      $userme              = $this->session->userdata('iduser');
      $iddr                = $this->Doctor_model->get_doctor_byuser($userme);
      $data['doctor']      = $this->Doctor_model->get_user_doctor($userme);
      $data['credentials'] = $this->Credentials_model->get_all_credentials_doctor($iddr);
      $data['documents']   = $this->Document_model->get_all_document2();
      $data['mymessage']   = null;
      $this->load->view('head');
      $this->load->view('doctor/content_credentials_dr',$data);
      $this->load->view('footer');
    }
    
}
