<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com

 	 Sitio es Banco o Tiro
 */
 
class DoctorService extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Doctorservice_model');
    } 

   

    function index()
    {
      $this->load->model('Doctor_model');
      $this->load->model('Doctorservice_model');
      $userme = $this->session->userdata('iduser');
      $iduserdoctor = $this->session->userdata('userdoctor');
      $doctor = $this->Doctor_model->get_doctor_byuser($userme);
      $theiddoctor = $doctor;
      $data['doctor'] = $this->Doctor_model->get_user_doctor($userme);
      $data['doctorservice'] = $this->Doctorservice_model->get_doctor_service2($theiddoctor);
      $data['mymessage'] = null;
      $this->load->view('head');
      $this->load->view('doctorservice/content_doctor_service',$data);
      $this->load->view('footer');
    }

    /*
     * Adding a new Ruta
     */
    function add()
    {   
 
      $params = array(
      'id_Doctor' => $this->input->post('idDoctor'),
      'Day_Week' => $this->input->post('day_week'),
      'Initial_Hour' => $this->input->post('hour'),
      'GMT' => $this->input->post('MYGMT'),
      );

      $ruta_id = $this->Doctorservice_model->add_doctor_service($params);
  
      $this->load->model('Document_model');
      $this->load->model('Doctor_model');
      $this->load->model('Doctorservice_model');
      $userme = $this->session->userdata('iduser');
      $data['doctor'] = $this->Doctor_model->get_user_doctor($userme);
      $doctor = $this->Doctor_model->get_doctor_byuser($userme);
      $theiddoctor = $doctor;
      $data['documents'] = $this->Document_model->get_all_document2();
      $data['doctorservice'] = $this->Doctorservice_model->get_doctor_service2($theiddoctor);
      $data['mymessage'] = "Schedule Add Succesfully";
      $this->load->view('head');
      $this->load->view('doctorservice/content_doctor_service',$data);
      $this->load->view('footer');
    }  

    /*
     * Editing a Doctor Service
     */

    function edit($id_doctor_service)
    {   
      
      $this->load->model('Doctor_model');
      $this->load->model('Doctorservice_model');
      $userme = $this->session->userdata('iduser');
      $iduserdoctor = $this->session->userdata('userdoctor');
      $doctor = $this->Doctor_model->get_doctor_byuser($userme);
      $theiddoctor = $doctor;
      $data['doctor'] = $this->Doctor_model->get_user_doctor($userme);
      $data['doctorservice'] = $this->Doctorservice_model->get_doctor_service_byid($id_doctor_service);
      $data['mymessage'] = null;
      $this->load->view('head');
      $this->load->view('doctorservice/content_edit_doctor_service',$data);
      $this->load->view('footer');
    }

    function update($id_doctor_service)
    { 
      $params = array(
      'id_Doctor' => $this->input->post('idDoctor'),
      'Day_Week' => $this->input->post('day_week'),
      'Initial_Hour' => $this->input->post('hour'),
      'GMT' => $this->input->post('MYGMT'),
      );
      $update_schedule = $this->Doctorservice_model->update_doctor_service($id_doctor_service,$params);
      if($update_schedule) {
        $data['mymessage'] = "Record Updated Succesfully";
      }
      else {
         $data['mymessage'] = "Oops we had a problem updating record";
      }
      $this->load->model('Doctor_model');
      $this->load->model('Doctorservice_model');
      $userme = $this->session->userdata('iduser');
      $iduserdoctor = $this->session->userdata('userdoctor');
      $doctor = $this->Doctor_model->get_doctor_byuser($userme);
      $theiddoctor = $doctor;
      $data['doctor'] = $this->Doctor_model->get_user_doctor($userme);
      $data['doctorservice'] = $this->Doctorservice_model->get_doctor_service_byid($id_doctor_service);
      $this->load->view('head');
      $this->load->view('doctorservice/content_edit_doctor_service',$data);
      $this->load->view('footer');
    } 

    /*
     * Deleting Ruta
     */
    function remove($id_doctor_service)
    {
      $delete_schedule = $this->Doctorservice_model->delete_doctorservice($id_doctor_service);
      if($delete_schedule) {
        $data['mymessage'] = "Record Deleted Succesfully";
      }
      else {
         $data['mymessage'] = "Oops we had a problem deleting record";
      }
      $this->load->model('Doctor_model');
      $this->load->model('Doctorservice_model');
      $userme = $this->session->userdata('iduser');
      $iduserdoctor = $this->session->userdata('userdoctor');
      $doctor = $this->Doctor_model->get_doctor_byuser($userme);
      $theiddoctor = $doctor;
      $data['doctor'] = $this->Doctor_model->get_user_doctor($userme);
      $data['doctorservice'] = $this->Doctorservice_model->get_doctor_service2($theiddoctor);
      $this->load->view('head');
      $this->load->view('doctorservice/content_doctor_service',$data);
      $this->load->view('footer');
    }
    
}
