<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
  class Doctor extends CI_Controller
  {
    function __construct()
    {
        parent::__construct();
        $this->load->model('Doctor_model');
    }
    
    function register()
    {
       /* I close session first */
       $this->session->unset_userdata('iduser');
       $this->session->unset_userdata('nameu');
       $this->session->unset_userdata('email');
       $this->session->unset_userdata('active');
       $this->session->sess_destroy();
       /*   */ 
       $this->load->model('Nationality_model');
       $this->load->model('Specialist_model');
       $this->load->model('Language_model');
       $this->load->model('MaritalStatus_model');
       $this->load->model('StreamTool_model');
       $this->load->model('User_model');

       $data['nationalities'] = $this->Nationality_model->get_all_nationality();
       $data['specialities'] = $this->Specialist_model->get_all_specialist();
       $data['languages'] = $this->Language_model->get_all_language();
       $data['marital'] = $this->MaritalStatus_model->get_all_maritalstatus2();
       $data['stream'] = $this->StreamTool_model->get_all_streamtool();
       $data['mymessage'] = null;
       //$this->load->view('head');
       $this->load->view('doctor/content_register_dr',$data);
       //$this->load->view('footer');
    }


    function profile()
    {
       $this->load->model('Doctor_model');
       $this->load->model('Nationality_model');
       $this->load->model('Specialist_model');
       $this->load->model('Language_model');
       $this->load->model('MaritalStatus_model');
       $this->load->model('StreamTool_model');
       $this->load->model('User_model');

       $userme = $this->session->userdata('iduser');
       $data['doctor'] = $this->Doctor_model->get_user_doctor($userme);
       $data['nationalities'] = $this->Nationality_model->get_all_nationality();
       $data['specialities'] = $this->Specialist_model->get_all_specialist();
       $data['languages'] = $this->Language_model->get_all_language();
       $data['marital'] = $this->MaritalStatus_model->get_all_maritalstatus2();
       $data['stream'] = $this->StreamTool_model->get_all_streamtool();
       $data['mymessage'] = null;
       //$this->load->view('head');
       $this->load->view('doctor/profile_dr',$data);
       //$this->load->view('footer');
    }
    function home()
    {
       $this->load->model('Nationality_model');
       $this->load->model('Specialist_model');
       $this->load->model('Language_model');
       $this->load->model('MaritalStatus_model');
       $this->load->model('StreamTool_model');
       $this->load->model('User_model');
       $this->laod->model('Booking_model');

       $data['nationalities'] = $this->Nationality_model->get_all_nationality();
       $data['specialities'] = $this->Specialist_model->get_all_specialist();
       $data['languages'] = $this->Language_model->get_all_language();
       $data['marital'] = $this->MaritalStatus_model->get_all_maritalstatus2();
       $data['stream'] = $this->StreamTool_model->get_all_streamtool();
       $data['mymessage'] = null;
       $this->load->view('head');
       $this->load->view('booking/doctors_booking',$data);
       $this->load->view('footer');
    }

    function credentials()
    {
       $this->load->model('Document_model');
       $this->load->model('Doctor_model');
       $this->load->model('Credentials_model');
       $this->load->model('User_model');

       $userme              = $this->session->userdata('iduser');
       $iddr                = $this->Doctor_model->get_doctor_byuser($userme);
       $data['doctor']      = $this->Doctor_model->get_user_doctor($userme);
       $data['credentials'] = $this->Credentials_model->get_all_credentials_doctor($iddr);
       $data['documents']   = $this->Document_model->get_all_document2();
       $data['mymessage']   = null;
       $this->load->view('head');
       $this->load->view('doctor/content_credentials_dr',$data);
       $this->load->view('footer');
    }

    function signup()
    {
      $error_form    = 0;
      /*
        Email Validation
      */
      $this->load->model('User_model');


      $thename       = $this->input->post('NameDr');
      $themiddlename = $this->input->post('MiddleName');
      $thelastname   = $this->input->post('LastName');
      $thefullname   = $thename." ".$themiddlename." ".$thelastname;
      $theemail      = $this->input->post('email');
      $thepassword   = $this->input->post('password');
      $thepassword2  = $this->input->post('password2');
      if($thepassword != $thepassword2) {
        $error_form    = 1;
      }
      $email_exists = $this->User_model->get_email($theemail);
      if($email_exists) {
        $error_form    = 2;
      }
      if($error_form == 0) { // No error in Password 
        $hash = password_hash($thepassword, 
        PASSWORD_DEFAULT,['cost'=>5]);
        $typeuser     = "D"; // Type of user Doctor

        $datai = array('Name' => $thefullname, 'Email' => $theemail, 
          'Type_User' => 'D', 'Password' => $hash, 'Active' => 0);
            $str = $this->db->insert_string('user', $datai);
            $insert_user = $this->db->simple_query($str);

        if($insert_user) 
        {
          $theiduser               = $this->db->insert_id();
          $thegender               = $this->input->post('Gender');
          $theidMaritalStatus      = $this->input->post('idMaritalStatus');
          $theidnationality        = $this->input->post('idNationality');
          $thedatebirth            = $this->input->post('DateBirth');
          $thephonenumber          = $this->input->post('PhoneNumber');
          $theidspecialist         = array();
          $theidspecialist         = $this->input->post('idSpecialist');
          $theexperienceyears      = $this->input->post('ExperienceYears');
          $theidlanguage           = array();
          $theidlanguage           = $this->input->post('idLanguage');
          $theidstreamtool         = $this->input->post('idStreamTool');
          //$thedrpicture            = $this->input->post('DrPicture');
          $theresum                = $this->input->post('Resum');
          /* Recording Especialist and Languages
              to a String Format Delimited by |
          */
          $StrEspecialist ="";
          $first=0;
          foreach($theidspecialist as $esp) {
            if($first==0) {
              $first=1;
              $StrEspecialist = $esp;
            }
            else {
              $StrEspecialist .= "|".$esp;
            }
          }
        
          $StrLanguage ="";
          $first=0;
          foreach($theidlanguage as $lan) {
            if($first==0) {
              $first=1;
              $StrLanguage = $lan;
            }
            else {
               $StrLanguage .= "|".$lan;
            }
          }
        
          $datadr = array(
            'id_User' => $theiduser,
            'First_Name' => $thename, 
            'Middle_Name' => $themiddlename, 
            'Last_Name' => $thelastname,
            'Gender' => $thegender,
            'id_Marital_Status' => $theidMaritalStatus,
            'id_Nationality' => $theidnationality,
            'Date_Birth' => $thedatebirth,
            'Phone_Number' => $thephonenumber,
            'id_Specialist' => $StrEspecialist,
            'Experience_Years' => $theexperienceyears,
            'id_Language' => $StrLanguage,
            'id_Stream_Tool' => $theidstreamtool, 
            'Resum' => $theresum);

          $strdr = $this->db->insert_string('doctor', $datadr);
          $insert_dr  = $this->db->query($strdr);
          $theiddr    = $this->db->insert_id();

          /* SEND EMAIL */
          $to = $theemail;
          $subject = "Welcome, Register Succesfully !";
            $txt = "We received your application #".$theiddr." You completed the first step. The next step is login and upload your credentials. When you completed this requirement we will review your application within 3 working days. In case of aprovement we will send you an email. Thank you.";
            $headers = "MIME-Version: 1.0" . "\r\n";
            $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
            // More headers
            $headers .= 'From: <admin@domain.com>' . "\r\n";
            $enviado = mail($to,$subject,$txt,$headers);

          if($insert_dr) {
            $directorio_destino = base_url()."upload/drs/";
            $miarchivo = $theiddr.$thedrpicture;
            $config['upload_path'] = "upload/drs/";
            $config['file_name'] = $theiddr.$thedrpicture;
            $config['allowed_types'] = 'gif|jpg|png|jpeg';
            $config['overwrite'] = true;
            $config['max_size'] = '100000';
            $config['max_width'] = '2000';
            $config['max_height'] = '2000';

            $this->load->library('upload',$config); 
            $upload_myfile = $this->upload->do_upload($thedrpicture);
            //if(!$upload_myfile) {
              /// Error
            //}
          }

        } // end insert user

        $tit['errorlogin'] = "Register Succesfully";
        $this->load->view('acceso/login',$tit);

      }
      else
      {

        $this->load->model('Nationality_model');
        $this->load->model('Specialist_model');
        $this->load->model('Language_model');
        $this->load->model('MaritalStatus_model');
        $this->load->model('StreamTool_model');

        $data['nationalities'] = $this->Nationality_model->get_all_nationality();
        $data['specialities'] = $this->Specialist_model->get_all_specialist();
        $data['languages'] = $this->Language_model->get_all_language();
        $data['marital'] = $this->MaritalStatus_model->get_all_maritalstatus2();
        $data['stream'] = $this->StreamTool_model->get_all_streamtool();
        if($error_form==1) {
          $data['mymessage'] = "Oops the passwords no match ";
        }
        if($error_form==2) {
          $data['mymessage'] = "Oops email exists already ";
        }
        $this->load->view('head');
        $this->load->view('doctor/content_register_dr',$data);
        $this->load->view('footer');
      }
    }

    function updatefoto() {

      $Result_Message = null;
      $myerror = true;
      $this->load->model('Doctor_model');
      $thedrpicture     = $this->input->post('myprofile');
      $iddoctor         = $this->input->post('iddoctor');
      
      $nombre_imagen    = "DR-".$iddoctor."-".$_FILES['mydocument']['name'];
      //$nombre_imagen    = "DR-".$iddoctor.$_FILES['mydocument']['type'];
      $tipo_imagen      = $_FILES['mydocument']['type'];
      $tamano_imagen    = $_FILES['mydocument']['size'];
      $carpeta_destino  = $_SERVER['DOCUMENT_ROOT']."/MEDICAL/upload/profile/";
      $Result_Message = "";
      if($tipo_imagen=="image/jpeg" || $tipo_imagen=="image/gif" ||
         $tipo_imagen=="image/png" || $tipo_imagen=="image/jpg" ||
         $tipo_imagen=="image/JPG" || $tipo_imagen=="application/pdf" )
      {
        
        $params = array('picture' => $nombre_imagen);

        $updatedr = $this->Doctor_model->update_doctor($iddoctor,$params);

        if($updatedr) {
           $image_final = $carpeta_destino.$nombre_imagen;
          move_uploaded_file($_FILES['mydocument']['tmp_name'], $image_final);
        }
        else {
           $Result_Message = "-- Update profile image not succesfull --";
        }
      }
      else
      {
        $Result_Message = "-- Oops wrong type image --".$tipo_imagen;
      }

      
      $this->load->model('Nationality_model');
      $this->load->model('Specialist_model');
      $this->load->model('Language_model');
      $this->load->model('MaritalStatus_model');
      $this->load->model('StreamTool_model');
      $this->load->model('User_model');

      $userme = $this->session->userdata('iduser');
      $data['doctor'] = $this->Doctor_model->get_user_doctor($userme);
      $data['nationalities'] = $this->Nationality_model->get_all_nationality();
      $data['specialities'] = $this->Specialist_model->get_all_specialist();
      $data['languages'] = $this->Language_model->get_all_language();
      $data['marital'] = $this->MaritalStatus_model->get_all_maritalstatus2();
      $data['stream'] = $this->StreamTool_model->get_all_streamtool();
      $data['mymessage'] = $Result_Message;
      $this->load->view('head');
      $this->load->view('doctor/profile',$data);
      $this->load->view('footer');
    }

    function update()
    {
      $myerror = true;
      $Result_Message = null;

      $this->load->model('Doctor_model');

      $iddoctor               = $this->input->post('iddoctor');
      $thename                = $this->input->post('NameDr');
      $themiddlename          = $this->input->post('MiddleName');
      $thelastname            = $this->input->post('LastName');
      $thefullname            = $thename." ".$themiddlename." ".$thelastname;
      $thegender              = $this->input->post('Gender');
      $theidMaritalStatus     = $this->input->post('idMaritalStatus');
      $theidnationality       = $this->input->post('idNationality');
      $thedatebirth           = $this->input->post('DateBirth');
      $thephonenumber         = $this->input->post('PhoneNumber');
      $theidspecialist        = array();
      $theidspecialist        = $this->input->post('idSpecialist');
      $theexperienceyears     = $this->input->post('ExperienceYears');
      $theidlanguage          = array();
      $theidlanguage          = $this->input->post('idLanguage');
      $theidstreamtool        = $this->input->post('idStreamTool');
      $theresum                = $this->input->post('Resum');
      /* Recording Especialist and Languages
        to a String Format Delimited by |
      */
      $StrEspecialist ="";
      $first=0;
      foreach($theidspecialist as $esp) {
        if($first==0) {
          $first=1;
          $StrEspecialist = $esp;
        }
        else {
          $StrEspecialist .= "|".$esp;
        }
      }
        
      $StrLanguage ="";
      $first=0;
      foreach($theidlanguage as $lan) {
        if($first==0) {
          $first=1;
          $StrLanguage = $lan;
        }
        else {
           $StrLanguage .= "|".$lan;
        }
      }
        
      $params = array(
        'First_Name' => $thename, 
        'Middle_Name' => $themiddlename, 
        'Last_Name' => $thelastname,
        'Gender' => $thegender,
        'id_Marital_Status' => $theidMaritalStatus,
        'id_Nationality' => $theidnationality,
        'Date_Birth' => $thedatebirth,
        'Phone_Number' => $thephonenumber,
        'id_Specialist' => $StrEspecialist,
        'Experience_Years' => $theexperienceyears,
        'id_Language' => $StrLanguage,
        'id_Stream_Tool' => $theidstreamtool, 
        'Resum' => $theresum);

      $updatedr = $this->Doctor_model->update_doctor($iddoctor,$params);

      if($updatedr) {
        $Result_Message = "-- Your Document Succesfully Updated --";
      }
      else {
         $Result_Message = "-- Update record not succesfull --";
      }
      
      $this->load->model('Nationality_model');
      $this->load->model('Specialist_model');
      $this->load->model('Language_model');
      $this->load->model('MaritalStatus_model');
      $this->load->model('StreamTool_model');
      $this->load->model('User_model');

      $userme = $this->session->userdata('iduser');
      $data['doctor'] = $this->Doctor_model->get_user_doctor($userme);
      $data['nationalities'] = $this->Nationality_model->get_all_nationality();
      $data['specialities'] = $this->Specialist_model->get_all_specialist();
      $data['languages'] = $this->Language_model->get_all_language();
      $data['marital'] = $this->MaritalStatus_model->get_all_maritalstatus2();
      $data['stream'] = $this->StreamTool_model->get_all_streamtool();
      $data['mymessage'] = $Result_Message;
      $this->load->view('head');
      $this->load->view('doctor/profile',$data);
      $this->load->view('footer');

    }


    function loadmydocument() 
    {
      $this->load->model("Credentials_model");
      $idDocument       = $this->input->post("idDocument");
      $idDoctor         = $this->input->post("idDoctor");
      $notes            = $this->input->post("notes");
      $nombre_imagen    = "DR_".$_FILES['mydocument']['name'];
      $tipo_imagen      = $_FILES['mydocument']['type'];
      $tamano_imagen    = $_FILES['mydocument']['size'];
      $carpeta_destino  = $_SERVER['DOCUMENT_ROOT']."/MEDICAL/upload/drs/";
      $Result_Message = "";
      if($tipo_imagen=="image/jpeg" || $tipo_imagen=="image/gif" ||
         $tipo_imagen=="image/png" || $tipo_imagen=="image/jpg" ||
         $tipo_imagen=="application/JPG" || $tipo_imagen=="application/pdf" )
      {
        $addcrede = array(
                'id_Document' => $idDocument,
                'id_Doctor'   => $idDoctor,
                'Document'    => $nombre_imagen,
                'Note'        => $notes,
        );
        //print_r($addcrede);
        
        $addc = $this->Credentials_model->add_credentials($addcrede);

        if($addc) {

          $image_final = $carpeta_destino."Doc-".$addc."-".$nombre_imagen;
          move_uploaded_file($_FILES['mydocument']['tmp_name'], $image_final);
          //echo "REVISAR todo bien<br>".$nombre_imagen." -- ".$tipo_imagen;
          $Result_Message = "-- Your Document Succesfully Uploaded --";
        }
        else
        {
          $Result_Message = "-- Oops Error Uploading Document --";
        }
      }
      else
      {
          $Result_Message = "-- Oops Error Type File not Allowed --";
      }
      $this->load->model('Document_model');
      $this->load->model('Doctor_model');
      $this->load->model('Credentials_model');
      $userme = $this->session->userdata('iduser');
      $data['doctor'] = $this->Doctor_model->get_user_doctor($userme);
      $data['documents'] = $this->Document_model->get_all_document2();
      $data['credentials'] = $this->Credentials_model->get_all_credentials_doctor($idDoctor);
      $data['mymessage'] = $Result_Message;
      $this->load->view('head');
      $this->load->view('doctor/content_credentials_dr',$data);
      $this->load->view('footer');
    }

    

    function login() {
      
      $theusername  = $this->input->post('username');
      $thepassword  = md5($this->input->post('password'));
      
      $approve      = $this->Acceso_model->get_acceso_adminc($theusername,$thepassword);
      
      if($approve)
      {

        $this->session->set_userdata('iduser',$approve['id_User']);
        $this->session->set_userdata('nameu',$approve['Name']);
        $this->session->set_userdata('email',$approve['Email']);

        $titulo['tit'] = "Doctor Dashboard";
        $titulo['tit2'] = "Detalles";
        $this->load->view('plantB11');
        $this->load->view('plantB2',$titulo);
        if($approve['TypeUser']=="D") {
          $this->load->view('doctor/dashbord',$data);
        }
        else {
          $this->load->view('client/index',$data);
        }
        $this->load->view('plantB4');
      }
      else
      {
        $tit['titulo1'] = "Invalid User o Password";
        $tit['titulo2'] = "Please Try Again";
        $this->load->model('Compania_model');
        $data['all_compania'] = $this->Compania_model->get_all_compania();
        $data['mensaje'] = "Usuario y/o Contraseña Invalido";
        $this->load->view('eencabmenu');
        $this->load->view('eencabmenu2',$tit);
        $this->load->view('logo',$data);
        $this->load->view('eencabmenu3');
      }    
    }
  } 