<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Acceso_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get usuario by idsuario
     */
    function get_acceso_admin($usuariop,$passwordp)
    {
         /*$this->db->where('usuario',$usuariop);
         $this->db->where('password',$passwordp);
         $query = $this->db->get('usuario')->result_array();
         */
         $consulta = "select id_Usuario, id_Cia, id_Obra, id_Rol, Usuario, Password, Nombre, Correo, UltimoFolio, Baja, Fecha from usuarios where Usuario='".$usuariop."' 
                 and password='".$passwordp."'";
         $consulta = $this->db->query($consulta);
         $resultado = $consulta->row_array();
         return $resultado;
    }

    function get_acceso_adminc($correop)
    {
         
         $consulta = "SELECT * FROM user WHERE Email='".$correop."'";
         $consulta = $this->db->query($consulta);
         $resultado = $consulta->row_array();
         return $resultado;
    }

    function get_acceso($usuariop,$passwordp,$idciap)
    {
         /*$this->db->where('usuario',$usuariop);
         $this->db->where('password',$passwordp);
         $query = $this->db->get('usuario')->result_array();
         */
         $consulta = "select id_Usuario, id_Cia, id_Obra, id_Rol, Usuario, Password, Nombre, Correo, UltimoFolio, Baja, Fecha from usuarios where Usuario='".$usuariop."' 
                 and password='".$passwordp."' and id_Cia = ".$idciap;
         $consulta = $this->db->query($consulta);
         $resultado = $consulta->row_array();
         return $resultado;
    }
    
    /*
     * Get all usuario
     */
    function get_all_acceso()
    {
        return $this->db->get('usuario')->result_array();
    }
    
    function autorizado()
    {
        $autoriza = true;
        if(!$this->session->userdata('nombreu'))
        {
            $tit['titulo1'] = "Acceso al Sistema";
            $tit['titulo2'] = "Ingrese Usuario y Password";
            //$this->load->view('encabezadomenu');
            //$this->load->view('encabezadomenu2',$tit);
            //$this->load->view('subencabezado');
            $this->load->view('usuario/index');
            //$this->load->view('encabezadomenu3');
            $autoriza = false;
        }
        return $autoriza;
                    
    }
    
   
}
