<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Booking_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get booking by id_Booking
     */
    function get_booking($id_booking)
    {
        return $this->db->get_where('booking',array('id_Booking'=>$id_booking))->row_array();
    }
    
    
    function get_all_booking()
    {
        $this->db->select('*');
        $this->db->from('booking');
        $this->db->order_by("id_Doctor");
        $this->db->order_by("id_Patient");
        $this->db->order_by("Date_Booking");
        return $this->db->get()->result_array();

    }
        
    /*
     * function to add new Booking
     */
    function add_booking($params)
    {
        $this->db->insert('booking',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update Booking
     */
    function update_booking($id_booking,$params)
    {
        $this->db->where('id_Booking',$id_booking);
        return $this->db->update('booking',$params);
    }
    
    /*
     * function to delete Booking
     */
    function delete_booking($id_booking)
    {
        return $this->db->delete('booking',array('id_Booking'=>$id_booking));
    }
}
