<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Credentials_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get Credentials by id_credentials
     */
    function get_credentials($id_credentials)
    {
        return $this->db->get_where('credentials',array('id_Credentials'=>$id_credentials))->row_array();
    }
        
    /*
     * Get all Credentials
     */
    function get_all_credentials2()
    {
        $this->db->select('*');
        $this->db->from('credentials');
        $this->db->order_by("id_Credentials");
        return $this->db->get()->result_array();

    }
    function get_all_credentials_doctor($id_doctor)
    {
        $consulta = "SELECT c.id_Credentials, c.id_Doctor, id_Document,(Select Name from document WHERE id_Document = c.id_Document) as requirement, c.Document, c.Note, c.Approve from credentials as c WHERE c.id_Doctor = ".$id_doctor.";";
        return $this->db->query($consulta)->result_array();
        
    }
        
    /*
     * function to add new Credentials
     */
    function add_credentials($params)
    {
        $this->db->insert('credentials', $params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update Credentials
     */
    function update_credentials($id_credentials,$params)
    {
        $this->db->where('id_Credentials',$id_credentials);
        return $this->db->update('credentials',$params);
    }
    
    /*
     * function to delete Credentials
     */
    function delete_credentials($id_credentials)
    {
        return $this->db->delete('credentials',array('id_Credentials'=>$id_credentials));
    }
}
