<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Document_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get document by id_document
     */
    function get_document($id_document)
    {
        return $this->db->get_where('document',array('id_Document'=>$id_document))->row_array();
    }
        
    /*
     * Get all Documents
     */
    function get_all_document2()
    {
        $this->db->select('*');
        $this->db->from('document');
        $this->db->order_by("id_Document");
        return $this->db->get()->result_array();

    }
    function get_all_document()
    {
        $this->db->order_by('name', 'asc');
        return $this->db->get('document')->result_array();
    }
        
    /*
     * function to add new Doctor
     */
    function add_document($params)
    {
        $this->db->insert('document',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update Doctor
     */
    function update_document($id_document,$params)
    {
        $this->db->where('id_Document',$id_document);
        return $this->db->update('document',$params);
    }
    
    /*
     * function to delete Doctor
     */
    function delete_document($id_document)
    {
        return $this->db->delete('document',array('id_Document'=>$id_document));
    }
}
