<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Language_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get language by id_Language
     */
    function get_language($id_language)
    {
        return $this->db->get_where('Language',array('id_Language'=>$id_language))->row_array();
    }
        
    /*
     * Get all Languages
     */
    function get_all_language2()
    {
        $this->db->select('*');
        $this->db->from('Language');
        $this->db->order_by("id_Language");
        return $this->db->get()->result_array();

    }
    function get_all_language()
    {
        $this->db->order_by('name', 'asc');
        return $this->db->get('Language')->result_array();
    }
        
    /*
     * function to add new Languages
     */
    function add_language($params)
    {
        $this->db->insert('Language',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update language
     */
    function update_language($id_language,$params)
    {
        $this->db->where('id_Language',$id_language);
        return $this->db->update('Language',$params);
    }
    
    /*
     * function to delete Language
     */
    function delete_language($id_language)
    {
        return $this->db->delete('Language',array('id_Language'=>$id_language));
    }
}
