<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class MaritalStatus_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get doctor by id_Marital_Status
     */
    function get_maritalstatus($id_maritalstatus)
    {
        return $this->db->get_where('marital_status',array('id_Marital_Status'=>$id_maritalstatus))->row_array();
    }
        
    /*
     * Get all Marital Status
     */
    function get_all_maritalstatus2()
    {
        $this->db->select('*');
        $this->db->from('marital_status');
        $this->db->order_by("id_Marital_Status");
        return $this->db->get()->result_array();

    }
    function get_all_maritalstatus()
    {
        $this->db->order_by('Name', 'asc');
        return $this->db->get('marital_status')->result_array();
    }
        
    /*
     * function to add new Marital Status
     */
    function add_maritalstatus($params)
    {
        $this->db->insert('marital_status',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update Marital Status
     */
    function update_maritalstatus($id_maritalstatus,$params)
    {
        $this->db->where('id_Marital_Status',$id_maritalstatus);
        return $this->db->update('marital_status',$params);
    }
    
    /*
     * function to delete Marital Status
     */
    function delete_maritalstatus($id_maritalstatus)
    {
        return $this->db->delete('marital_status',array('id_Marital_Status'=>$id_maritalstatus));
    }
}
