<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Notification_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
   
    function add_notification($params)
    {
        $this->db->insert('notification',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update Booking
     */
    function update_notification($id_notification,$params)
    {
        $this->db->where('id_Notification',$id_notification);
        return $this->db->update('notification',$params);
    }
    
    /*
     * function to delete Booking
     */
    function delete_notification($id_notification)
    {
        return $this->db->delete('notification',array('id_Notification'=>$id_notification));
    }
}
