<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Patient_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get patient by id_doctor
     */
    function get_patient($id_patient)
    {
        return $this->db->get_where('patient',array('id_Patient'=>$id_patient))->row_array();
    }
    
    function get_patient_byuser($id_user)
    {
        $consulta = "SELECT id_Patient FROM patient WHERE id_User = ".$id_user.";";
        $query = $this->db->query($consulta);
        if ($query->num_rows() > 0)
        {
            foreach ($query->result() as $row)
            {
                $idpatient = $row->id_Patient;
            }
        }
        return $idpatient;
    }  
    /*
     * Get all Patient
     */
    function get_all_patient2()
    {
        $this->db->select('*');
        $this->db->from('patient');
        $this->db->order_by("id_Patient");
        return $this->db->get()->result_array();

    }
    function get_all_patient()
    {
        $this->db->order_by('Middle_Name', 'asc');
        $this->db->order_by('First_Name', 'asc');
        return $this->db->get('patient')->result_array();
    }

    function get_user_patient($id_user)
    {
        $this->db->where('id_User',$id_user);
        return $this->db->get('patient')->result_array();
    }
        
    /*
     * function to add new Patient
     */
    function add_patient($params)
    {
        $this->db->insert('patient',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update Patient
     */
    function update_patient($id_patient,$params)
    {
        $this->db->where('id_Patient',$id_patient);
        return $this->db->update('patient',$params);
    }
    
    /*
     * function to delete Patient
     */
    function delete_patient($id_patient)
    {
        return $this->db->delete('patient',array('id_Patient'=>$id_patient));
    }
}
