<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class StreamTool_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get obra by id_Stream_Tools
     */
    function get_streamtool($id_streamtool)
    {
        return $this->db->get_where('stream_tool',array('id_Stream_Tool'=>$id_streamtool))->row_array();
    }
        
    /*
     * Get all Stream Tools
     */
    function get_all_streamtool()
    {
        $this->db->order_by('id_Stream_Tool', 'asc');
        return $this->db->get('stream_tool')->result_array();
    }
        
    /*
     * function to add new Stream Tools
     */
    function add_streamtool($params)
    {
        $this->db->insert('stream_tool',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update Stream Tools
     */
    function update_streamtool($id_streamtool,$params)
    {
        $this->db->where('id_Stream_Tool',$id_sitio);
        return $this->db->update('stream_tool',$params);
    }
    
    /*
     * function to delete Stream Tools
     */
    function delete_streamtool($id_streamtool)
    {
        return $this->db->delete('stream_tool',array('id_Stream_Tool'=>$id_streamtool));
    }
}
