<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get usuario by idusuario
     */
    function get_user($iduser)
    {
        return $this->db->get_where('user',array('id_User'=>$iduser))->row_array();
    }

    

    function get_email($themail)
    {
        $hay = false;
        $sql ="SELECT Email FROM user where Email='".$themail."'";
        $query = $this->db->query($sql);
        if($query->num_rows() > 0) {
            $hay = true;
        } 
        return $hay;
    }
        
    /*
     * Get all usuario
     */
    function get_all_usuario()
    {
        $this->db->order_by('id_User', 'desc');
        return $this->db->get('user')->result_array();
    }

    // Condtion  0="No active" 1= "active"
    function get_all_usuario_condition($condition)
    {
        $this->db->order_by('id_User', 'desc');
        $this->db->where('Active',$condition);
        return $this->db->get('user')->result_array();
    }

    /*
     * function to add new user
     */
    function add_user($params)
    {
        $this->db->insert('user',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user
     */
    function update_user($iduser,$params)
    {
        $this->db->where('id_User',$iduser);
        return $this->db->update('user',$params);
    }

    function update_password($themail,$params)
    {
        $this->db->where('Email',$themail);
        return $this->db->update('user',$params);
    }
    
    /*
     * function to delete usuario
     */
    function delete_usuario($iduser)
    {
        return $this->db->delete('user',array('id_User'=>$iduser));
    }
}
